### ISSUE TITLE
Is the check for the Content-Type HTTP header parameter too strict?

### ISSUE THREAD

**Issue by mikrobi** [weavora/wrest#2]
In WHttpRequest::parseJsonParams you check the content-type. JSON parameters are only parsed if it is set to 'application/json'. When I used a REST client to test my app, it was not working as the content-type was set to 'application/json; charset=UTF-8'.

P.S. I like your extension thanks for your work!!

**Comment by slavchoo** [comment]
Done. Thanks for your feedback.

**Comment by SteffenL** [comment]
Hi! I guess I could have sent a pull request (for credit's sake) but thanks for using my code anyway. :)
