### ISSUE TITLE
Automatically attach WRestModelBehavior to models

### ISSUE THREAD

**Issue by mikrobi** [weavora/wrest#3]
In your documentation you suggest to add the WRestModelBehavior to all model classes by default. I ran into some problems using Gii for creatiing CRUD templates for model classes that had some thing like this:

```
public function behaviors()
  {
     return array(
         ...
        'RestModelBehavior' => array(
           'class' => 'WRestModelBehavior',
        )
         ...
     );
}
```

Additionally its a repitive and annoying task to add or modify the behaviors() method of all your model classes. I'd suggest to attach the WRestModelBehavior autmatically in the WRestController::getModel() method:

```
public function getModel($scenario = '')
{
    ...
    if ($id) {
        $model = $modelName::model()->findByPk($id);
        ....
    } else {
        $model = new $modelName();
    }
    // Automatically attach WRestModelBehavior behaviour
    if($model) {
        $model->attachBehavior('wrest',new WRestModelBehavior());
    }
    if ($scenario && $model)
        $model->setScenario($scenario);
    return $model;
}
```

In my opinion this is a cleaner solution. What do you think about this?

**Comment by silrayn** [comment]
Hello, just a quick note. You can actually create a model called RestModel with the behavior defined and have gii extend that model instead of the regular model.
